### PR TITLE
Remove insecure functionality

### PR DESCRIPTION
**Pull request by ghost**
This PR removes insecure functionality of the library in relation to [this](https://github.com/jitsi/jitsi-meet/security/advisories/GHSA-45ff-37jm-xjfx) recent jitsi-meet security advisory. The change essentially removes the `decode` functionality of the library, making it harder to release unverified plaintext accidentally. The main changes are:
* Remove the `decode` function.
* Use `cjson.safe` instead of plain `cjson`to safeguard against parsing vulnerabilities. 
* Use `basexx` instead of manual bas64 to base64url conversion.
* Add the feature of optionally verifying the issuer and audience claims of the token. This is first of all good practice, and second of all allows for simplification on the `jitsi-meet` side. 
* Add doc comments to all functions.
* Adapted and extended tests.
* Bumped version to 3.0 as this is a breaking API change.

### CODE REVIEW

**Review by saghul — APPROVED** [review]
LGTM, nice work! @sawall can you also PTAL?

**Comment by sawall** [comment]
@philip-cc Looks fantastic to me.  Thanks especially for the docs and new cases!

@saghul I made a PR to pin luajwtjitsi to v2 in the jitsi-meet debian build scripts so nothing wonky goes on with out builds until we get the jitsi-meet PR in: https://github.com/jitsi/jitsi-meet/pull/10262
So please approve/merge that before merging this one.

**Comment by ghost** [comment]
@saghul what's the status on getting this merged?

**Comment by saghul** [comment]
@sawall can you also take a look please?

**Comment by sawall** [comment]
@saghul oops, thought you were going to handle that.

**Comment by saghul** [comment]
Yeah sorry about that, I've been swamped lately.

**Pull request merged**
